### ISSUE TITLE
ISO fails to build

### ISSUE THREAD

**Issue by array-in-a-matrix** [ArseLinuxOS-Development/ArseLinuxOS-ISO#1]
Building with docker or directly on host fails due to the pacman configuration being missing.

**Comment by array-in-a-matrix** [comment]
(without docker) creating/copying the missing `pacman.conf` results in an error later on after syncing packages: 
```
error: target not found: arse-hooks
==> ERROR: Failed to install packages to new root
```

**Comment by LiamAEdwards** [comment]
I've fixed this, it was referencing a package I was testing and I had  forgotten to remove from the `packages.x86_64` file.  The `pacman.conf` file it was looking for has been copied into the parent dir.

**Comment by LiamAEdwards** [comment]
Builds should work now, so let me know if you have any more issues.
