### ISSUE TITLE
Matrix room

### ISSUE THREAD

**Issue by array-in-a-matrix** [ArseLinuxOS-Development/ArseLinuxOS-ISO#15]
Is there a matrix room for discussion over the OS's development?

**Comment by LiamAEdwards** [comment]
There is! I had to rebuild my server so it was temporarily down. 

The link on the github repo works for me so let me know if you have any issues.

**Comment by LiamAEdwards** [comment]
Actually, I've created a room on a seperate instance so we don't lose anything in future. 

https://matrix.to/#/#arselinux-dev:envs.net

**Comment by array-in-a-matrix** [comment]
nice, there is no need to recreate the room as long as a known-to-be-stable homeserver is federating with it. Offline HS will just fetch the missed events from it when they go back online.
