### ISSUE TITLE
Install script does not correctly set up the new user environment

### ISSUE THREAD

**Issue by LiamAEdwards** [ArseLinuxOS-Development/ArseLinuxOS-ISO#16]
When a new user is created the script is supposed to, but does not.

- `chown` the user directory with their permissions
- Grab the `/etc/skel` files that enable the desktop

Need to find a solution.

Issue lies somewhere on line 638 in the `installer.sh` script.

```
# Set user passwd
print "Set user password"
arch-chroot /mnt useradd -m ${user} -G wheel -k /etc/skel
arch-chroot /mnt /bin/passwd "$user"
arch-chroot /mnt /bin/chown -R ${user}:${user} /home/${user}
arch-chroot /mnt /bin/rsync -av /etc/skel/ /home/${user}
```

The rsync command is an attempt to sync through contents of skel and the user directory but that does not work.

**Comment by array-in-a-matrix** [comment]
where is the installer script located?

**Comment by LiamAEdwards** [comment]
The issue was that I was creating the users home directory with `zfs` so when the `useradd` ran, it didn't seem to grab the data from `/etc/skel/` or `chown` the home dir.
