### ISSUE TITLE
Stuck on boot

### ISSUE THREAD

**Issue by array-in-a-matrix** [ArseLinuxOS-Development/ArseLinuxOS-ISO#5]
Systemd gets suck on boot after trying to boot a graphical interface (currently there isn't any yet).
System should boot into a login shell if it can't start a graphical shell.

![SS_12 02 2023_12:33:33](https://user-images.githubusercontent.com/78233840/218327083-ff7eb786-0162-4349-8155-e30f95d1c8a5.png)

**Comment by LiamAEdwards** [comment]
This is an issue I am struggling with, I want it to boot into a graphical user environment with XFCE or similar, however even after installing and telling it to boot it seems to get stuck. 

Reckon you can put some of your Arch expertise to the test and get it booting into a live user environment?
